### ISSUE TITLE
make check Fails

### ISSUE THREAD

**Issue by Vyoma-M** [hpc4cmb/libconviqt#10]
Hello,
I encountered some issues while running `make check`. Please find attached the log file from `make check` and the log file from `./configure`.
[test-suite.log](https://github.com/hpc4cmb/libconviqt/files/5293485/test-suite.log)
[libconviqt_configure.log](https://github.com/hpc4cmb/libconviqt/files/5293490/libconviqt_configure.log)

**Comment by keskitalo** [comment]
Looks like you are compiling against `cfitsio` that was installed in a non-standard location. You will have to adjust your `LD_LIBRARY_PATH` accordingly. This is not a `libonviqt` issue.
